-- This file is generated by automatic tools.
library ieee;
use ieee.std_logic_1164.all;
use work.eecs361_gates.all;

entity or_16 is
  port (
    x:in std_logic_vector(15 downto 0);
    z:out std_logic
  );
end or_16;

architecture structural of or_16 is

signal a,b,c,d,e,f,g,h,i,j,k,l,m,n,o:std_logic;



begin
    
    or1:or_gate port map(x(0),x(1),a);
    or2:or_gate port map(x(2),x(3),b);
    or3:or_gate port map(x(4),x(5),c);
    or4:or_gate port map(x(6),x(7),d);
    or5:or_gate port map(x(8),x(9),e); 
    or6:or_gate port map(x(10),x(11),f);
    or7:or_gate port map(x(12),x(13),g);
    or8:or_gate port map(x(14),x(15),h);
    or9:or_gate port map(a,b,i);
    or10:or_gate port map(c,d,j);
    or11:or_gate port map(e,f,k);
    or12:or_gate port map(g,h,l);
    or13:or_gate port map(i,j,m);
    or14:or_gate port map(k,l,n);
    or15:or_gate port map(m,n,z); 
     
end structural;


